import {
  GET_ALL_PRODUCTS,
  SEARCH_PRODUCT_BY_ID,
  SEARCH_PRODUCT_BY_SKU
} from './queries'
import {
  CREATE_PRODUCT,
  UPDATE_PRODUCT,
  DELETE_PRODUCT_BY_ID
} from './mutations'

export {
  GET_ALL_PRODUCTS,
  SEARCH_PRODUCT_BY_ID,
  SEARCH_PRODUCT_BY_SKU,
  CREATE_PRODUCT,
  UPDATE_PRODUCT,
  DELETE_PRODUCT_BY_ID
}
